name    'puppet-cic-install'
version '0.1.0'
source  'https://github.com/PierrickI3/puppet-cic-install'
author  'Pierrick Lozach'
license 'Apache License 2.0'
summary 'Module to install CIC silently'
description 'Puppet module to install CIC silently. The Setup Assistant does not get executed.'
project_page  'https://github.com/PierrickI3/puppet-cic-install'
