name    'cicserver'
version '0.1.0'
source  'https://github.com/PierrickI3/inin-cicserver'
author  'Pierrick Lozach'
license 'Apache License 2.0'
summary 'Module to install CIC silently'
description 'Puppet module to install CIC, Interaction Firmware and Media Server silently. The Setup Assistant does not get executed.'
project_page  'https://github.com/PierrickI3/inin-cicserver'

dependency 'puppetlabs/dism', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 3.1.0'
dependency 'puppetlabs/registry', '>= 1.0.3'
