class {'cicserver::icsurvey':
  path                  => 'C:/I3/IC/manifest/newsurvey.icsurvey',
  installnodomain       => true,
  organizationname      => 'organizationname',
  locationname          => 'locationname',
  sitename              => 'sitename',
  dbreporttype          => 'db',
  dbtablename           => 'I3_IC',
  dialplanlocalareacode => '317',
  emailfbmc             => true,
  recordingspath        => 'C:/I3/IC/Recordings',
  sipnic                => 'Ethernet',
  outboundaddress       => '3178723000',
  defaulticpassword     => '1234',
  licensefile           => 'C:/vagrant-data/cic-license.i3lic',
  template              => 'cicserver/DefaultSurvey.ICSurvey.erb',
}